### ISSUE TITLE
Lessons file names are different from the fast.ai version 2.

### ISSUE THREAD

**Issue by denis-trofimov** [naviarh/fastai-lessons-russian#1]
## Would it be convinient to name files in a same way as in updated course?
```sh
ls ~/p/fastai/courses/dl1/lesson*
courses/dl1/lesson1-breeds.ipynb       
courses/dl1/lesson1.ipynb        
courses/dl1/lesson1-rxt50.ipynb
courses/dl1/lesson1-vgg.ipynb
courses/dl1/lesson2-image_models.ipynb
courses/dl1/lesson3-rossman.ipynb
...
```

**Comment by naviarh** [comment]
I apologize for the long silence.
Initially, I studied the course on video lectures, peeping into the original Jupiter Notebooks, and wrote the Noteboks in its own way, and as a result there is no exact correspondence between them, in short, in some detail. Then decided to publish on githab, indicating links to original materials. My publications are useful for Russian-speaking people who do not know English, but who want to understand the essence of educational materials.

**Comment by denis-trofimov** [comment]
@naviarh Thank you for reply.
I have completed part 1.
I am not interested in the issue anymore.
